### ISSUE TITLE
`--profile` option to `cargo openvm build` doesn't do anything

### ISSUE THREAD

**Issue by matthiasgoergens** [openvm-org/openvm#1141]
`struct BuildArgs` has an entry `profile` but it's not connected to anything.

`struct GuestOptions` has an entry `profile`, but it's always the default (which is release), and never set anywhere.

I suggest we should somehow connect the two, and perhaps set up a test or two?

As a workaround setting the environment variable `OPENVM_BUILD_DEBUG="1"` works to get the `dev` build.  But apart from `dev` and `release` no other profiles are available at the moment.

**Comment by jonathanpwang** [comment]
Good catch, thanks! Will fix ASAP

**Comment by matthiasgoergens** [comment]
Thanks for the quick fix!

Btw, is there any way to run clippy on the guest program? For my project I'm doing that by manually running it, but the right incantations for that might change over time and it's rather tedious.

(And clippy isn't the only thing you might want to run. Perhaps we can have a way to run an (almost) arbitrary cargo command in the right context?)

**Comment by jonathanpwang** [comment]
Yea so guest crates are still normal Rust crates: you should still be able to run normal cargo commands like `cargo check` or `cargo clippy` directly. It's just that `cargo build` will build for your host (e.g., x86, aarch) target, whereas `cargo openvm build` adds extra flags to build for the zkVM target.

So you should be able to do all the normal things with any Rust project. We don't add guest programs to our workspace just to keep some separation since the guest programs are for testing.

If you run into any problems with the above, feel free to ask in Telegram! Or open another github issue, and we'll try to either add to the book or update functionality to support it.

**Comment by matthiasgoergens** [comment]
> If you run into any problems with the above, feel free to ask in Telegram! Or open another github issue, and we'll try to either add to the book or update functionality to support it.

Sorry, could you put the Telegram contact details somewhere in the Readme or so?  It seems I'm a bit blind.  Thanks!

**Comment by jonathanpwang** [comment]
> Sorry, could you put the Telegram contact details somewhere in the Readme or so? It seems I'm a bit blind. Thanks!

Added!
